### PR TITLE
Misc changes

### PR DESCRIPTION
**Pull request by mattdrees**
Some misc changes.

Probably the most important is bumping the 'max-connections' value from 10 to 500. We are hoping this will reduce the 'EOF'/disconnect messages we've seen.

This also includes some commits that I had made locally and were part of the image I pushed to dockerhub, but had not pushed to github.

### CODE REVIEW

**Comment by mattdrees** [comment]
@mikealbert want to take a look at these?

**Comment by mikealbert** [comment]
@mattdrees looks good so far.  Only question I have is about the testing process.  I have the local syslog-splunk container running, but when I build and run the syslog-splunk-tester container, I don't see any data show up in splunk (searched for 'paddpadd' didn't return results).  Might be something I'm doing wrong on my end.  Here's what my local output looks like

```
mikealbert@rmbp~/Development/syslog-splunk/test$ ./run.sh
Host: 0645e0caaf14
IP: 172.17.0.88
Target: syslog.uscm.org
Testing TCP...
average rate = 7.37 msg/sec, count=15, time=2.034, (average) msg size=254, bandwidth=1.83 kB/sec
Testing UDP Multiline
```

**Comment by mattdrees** [comment]
Yeah, I should document that a little better.

So your test actually does show results in splunk; [these events](https://splunk.ccci.org:8000/en-US/app/search/search?earliest=1438171200&latest=1438174800&q=search%20index%3Daws-ecs%20paddpaddpaddpaddpaddpaddpaddpaddpaddpaddpaddpaddpa&sid=1438208248.17506) are yours, I am pretty sure.

The problem is you have to search for the whole string (`PADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPA`) and not just a substring. However, if you start typing `index=aws-ecs PADDP` in the search bar, a popup with a 'Matching searches' section will show, and you can click that.


That all said, `run.sh` didn't test your syslog-splunk container. It tested syslog.uscm.org.
Next time, run `run_test_locally.sh`, which will test your own syslog-splunk.

**Comment by mattdrees** [comment]
I made it easier to search for the test results in splunk, and added a section on testing to the readme.

**Comment by mattdrees** [comment]
@mikealbert look ok?

**Comment by mikealbert** [comment]
@mattdrees Sorry for the delay.  Thanks for clarifying the testing steps.

Don't know what process you all usually follow for pull requests, so let me know if you need me to merge or do anything else.

**Comment by mattdrees** [comment]
no worries.

The 'process' isn't very formal. Usually the reviewer will say "looks good to me" or some variant, like :+1:  or LGTM.

As far as who merges -- usually I do the merge if I'm going to be the one who deploys it. If it's someone else, I'll let them do the merge. It doesn't matter as much whether I'm the author or the reviewer.
But I'm not sure if others follow this pattern too, or if this is just what I do. :-)

Thanks for the review!

**Pull request merged**
