### PR TITLE
MISC-230 Compress log files daily

### PR DESCRIPTION
**Pull request by mattdrees**
This PR compresses the log files that are kept around in the splunk container for 7 days. This is to keep the container's disk space usage lower than the 10G limit. In the past 10G was plenty big for 7 days, but apparently recently we've been generating more logs than before.

Compressing these log files should give us quite a bit more room to operate without having to increase the 10G limit.

### CODE REVIEW

**Comment by mattdrees** [comment]
@mikealbert could you review for me?

**Comment by mattdrees** [comment]
@bbakercru I converted the crontab scripts into more robust scripts, as you suggested in hipchat. Can you look them over?

I removed some things that I didn't understand, like the grep-based double-checking and the background ampersand that I asked about in hipchat. If you think these are important, maybe you can help me understand them.

**Comment by bbakercru** [comment]
Reviewed the script.  Where else does the forwarder pull logs from.  If only from /var/log/syslog, then I would suggest that the LOGRESULTS path be /var/log/syslog/syslog-compression.log OR adjust the forwarder inputs.conf file to include it.

**Comment by bbakercru** [comment]
Correct - the script was a quick copy and past - as noted above, there are needed changes that I found after putting it together.  I just wanted to show an external script that could be called to control the failure message that would feed a splunk alert.  Please use what ever works for you.

**Comment by mattdrees** [comment]
So, the primary source of logs is `/var/log/syslog` -- this are where the various application logs go; syslog-ng writes log files here when it gets remote syslog messages. it is monitored by the `[monitor:///var/log/syslog]` section in inputs.conf.

The `/var/log` dir contains log files that are generated by the syslog-container itself -- supervisord boot logs, syslog-ng internal logs, and now the cron job logs. These are all monitored by the [monitor:///var/log] section in inputs.conf.

Does that sound reasonable?

**Comment by mattdrees** [comment]
That is, I don't think LOGRESULTS should change, and I think inputs.conf is already correct.

**Comment by bbakercru** [comment]
yes and yes - I took a moment to view your inputs.conf file (should of did
that earlier).

On Wed, Feb 3, 2016 at 10:45 AM, Matt Drees <notifications@github.com>
wrote:

> That is, I don't think LOGRESULTS should change, and I think inputs.conf
> is already correct.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CruGlobal/syslog-splunk/pull/5#issuecomment-179301497>
> .
>



-- 
*Bill Baker*
System Administrator
Digital Products & Services, Cru
407-854-1458
bill.baker@cru.org

**Comment by mattdrees** [comment]
Great, thanks for the review, Bill!

**Comment by bbakercru** [comment]
You are welcome - let me know when that data (results log) is coming in.  I
can setup another splunk alert on it if you like?

On Wed, Feb 3, 2016 at 11:21 AM, Matt Drees <notifications@github.com>
wrote:

> Great, thanks for the review, Bill!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CruGlobal/syslog-splunk/pull/5#issuecomment-179321494>
> .
>



-- 
*Bill Baker*
System Administrator
Digital Products & Services, Cru
407-854-1458
bill.baker@cru.org

**Comment by mattdrees** [comment]
Sounds good; I will let you know.

An alert for failed cron jobs would be great, thanks!

**Pull request merged**
